import type { Metadata } from "next";
import { Cormorant_Garamond, Poppins } from "next/font/google";
import "./globals.css";
import type { PropsWithChildren } from "react";

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant-garamond",
  weight: ["400"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const className = `antialiased bg-neutral-900 text-neutral-400 ${poppins.variable} ${cormorantGaramond.variable}`;

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={className}>
      <body>{children}</body>
    </html>
  );
}
